import fs from 'fs';
import path from 'path';
import slugify from 'slugify';
import { Product } from '@/types';

// Load invalid images list (generated by scripts/filter-bad-images.js)
let invalidImageSet: Set<string> | null = null;
function getInvalidImages(): Set<string> {
  if (!invalidImageSet) {
    try {
      const filePath = path.join(process.cwd(), 'src', 'data', 'invalid-images.json');
      const data = JSON.parse(fs.readFileSync(filePath, 'utf-8')) as string[];
      invalidImageSet = new Set(data);
    } catch {
      invalidImageSet = new Set();
    }
  }
  return invalidImageSet;
}

const TEAM_ALIASES: Record<string, string> = {
  // Premier League
  'man u': 'Manchester United',
  'man utd': 'Manchester United',
  'manchester utd': 'Manchester United',
  'manchester': 'Manchester United', // often just called Manchester in generic folders
  'man city': 'Manchester City',
  'arsenal': 'Arsenal',
  'chelsea': 'Chelsea',
  'liverpool': 'Liverpool',
  'tottenham': 'Tottenham Hotspur',
  'tottenham hotspur': 'Tottenham Hotspur',
  'aston': 'Aston Villa',
  'aston villa': 'Aston Villa',
  'newcastle': 'Newcastle United',
  'newcastle united': 'Newcastle United',
  'leeds': 'Leeds United',
  'leeds united': 'Leeds United',
  'leicester': 'Leicester City',
  'leicester city': 'Leicester City',
  
  // La Liga
  'barca': 'FC Barcelona',
  'barcelona': 'FC Barcelona',
  'fc barcelona': 'FC Barcelona',
  'real': 'Real Madrid',
  'real madrid': 'Real Madrid',
  'atm': 'Atletico Madrid',
  'atletico': 'Atletico Madrid',
  'atletico madrid': 'Atletico Madrid',
  'atlético de madrid': 'Atletico Madrid',
  'bilbao': 'Athletic Bilbao',
  'athletic bilbao': 'Athletic Bilbao',
  'betis': 'Real Betis',
  'seville': 'Sevilla',
  'sevilla': 'Sevilla',
  'valencia': 'Valencia',
  
  // Serie A
  'juve': 'Juventus',
  'juventus': 'Juventus',
  'ac': 'AC Milan',
  'milan': 'AC Milan',
  'ac milan': 'AC Milan',
  'inter': 'Inter Milan',
  'inter milan': 'Inter Milan',
  'naples': 'Napoli',
  'napoli': 'Napoli',
  'roma': 'AS Roma',
  'lazio': 'Lazio',
  'fiorentina': 'Fiorentina',
  
  // Ligue 1
  'paris saintgermain': 'PSG',
  'paris saint germain': 'PSG',
  'paris': 'PSG',
  'psg': 'PSG',
  'ol': 'Olympique Lyonnais',
  'lyon': 'Olympique Lyonnais',
  'om': 'Olympique de Marseille',
  'marseille': 'Olympique de Marseille',
  'lille': 'LOSC Lille',
  'lens': 'RC Lens',
  'monaco': 'AS Monaco',
  'rennes': 'Stade Rennais',
  
  // Bundesliga
  'bayern': 'Bayern Munich',
  'bayern munich': 'Bayern Munich',
  'bvb': 'Borussia Dortmund',
  'dortmund': 'Borussia Dortmund',
  'borussia dortmund': 'Borussia Dortmund',
  'leverkusen': 'Bayer Leverkusen',
  'bayer leverkusen': 'Bayer Leverkusen',
  'leipzig': 'RB Leipzig',
  
  // Other Clubs
  'ajax': 'Ajax Amsterdam',
  'psv': 'PSV Eindhoven',
  'feyenoord': 'Feyenoord',
  'benfica': 'Benfica',
  'porto': 'FC Porto',
  'sporting': 'Sporting CP',
  'sporting cp': 'Sporting CP',
  'lisbon': 'Sporting CP',
  'celtic': 'Celtic FC',
  'rangers': 'Rangers FC',
  'galata': 'Galatasaray',
  'galatasaray': 'Galatasaray',
  'fenerbahçe': 'Fenerbahce',
  'fenerbahce': 'Fenerbahce',
  'besiktas': 'Besiktas',
  'boca': 'Boca Juniors',
  'boca juniors': 'Boca Juniors',
  'river': 'River Plate',
  'river plate': 'River Plate',
  'flamengo': 'Flamengo',
  'corinthians': 'Corinthians',
  'palmeiras': 'Palmeiras',
  'sao paulo': 'Sao Paulo',
  'miami': 'Inter Miami',
  'inter miami': 'Inter Miami',
  'la galaxy': 'LA Galaxy',
  'al nassr': 'Al Nassr',
  'al hilal': 'Al Hilal',
  'al ahli': 'Al Ahli',
  
  // Nations
  'france': 'France',
  'french': 'France',
  'argentine': 'Argentine',
  'argentina': 'Argentine',
  'bresil': 'Brésil',
  'brazil': 'Brésil',
  'brazilian': 'Brésil',
  'allemagne': 'Allemagne',
  'germany': 'Allemagne',
  'german': 'Allemagne',
  'espagne': 'Espagne',
  'spain': 'Espagne',
  'spanish': 'Espagne',
  'italie': 'Italie',
  'italy': 'Italie',
  'italian': 'Italie',
  'angleterre': 'Angleterre',
  'england': 'Angleterre',
  'english': 'Angleterre',
  'portugal': 'Portugal',
  'pays-bas': 'Pays-Bas',
  'netherlands': 'Pays-Bas',
  'dutch': 'Pays-Bas',
  'belgique': 'Belgique',
  'belgium': 'Belgique',
  'belgian': 'Belgique',
  'maroc': 'Maroc',
  'morocco': 'Maroc',
  'moroccan': 'Maroc',
  'algerie': 'Algérie',
  'algeria': 'Algérie',
  'algerian': 'Algérie',
  'senegal': 'Sénégal',
  'cameroun': 'Cameroun',
  'cameroon': 'Cameroun',
  'cote divoire': 'Côte d\'Ivoire',
  'ivory coast': 'Côte d\'Ivoire',
  'japon': 'Japon',
  'japan': 'Japon',
  'japanese': 'Japon',
  'mexique': 'Mexique',
  'mexico': 'Mexique',
  'mexican': 'Mexique',
  'colombie': 'Colombie',
  'colombia': 'Colombie',
  'uruguay': 'Uruguay',
  'chili': 'Chili',
  'chile': 'Chili'
};

export const TOP_CLUBS = [
  'Real Madrid', 'FC Barcelona', 'PSG', 'Manchester City', 'Arsenal', 
  'Manchester United', 'Liverpool', 'Chelsea', 'Bayern Munich', 
  'Juventus', 'AC Milan', 'Inter Milan', 'Atletico Madrid', 'Borussia Dortmund',
  'Olympique de Marseille', 'Olympique Lyonnais'
];

export const TOP_NATIONS = [
  'France', 'Argentine', 'Brésil', 'Allemagne', 'Espagne', 
  'Italie', 'Angleterre', 'Portugal', 'Maroc', 'Algérie', 'Sénégal'
];

function normalizeTeam(team: string): string {
  let t = team.toLowerCase().trim();
  
  // Pre-clean common garbage words and residual numbers from folder names
  t = t.replace(/['.]s\b/g, '')
       .replace(/^[.\s]+/, '') // Remove leading dots or spaces
       .replace(/^\d{4,6}/, '') // Remove leading dates like 2526, 202324, 0607
       .replace(/team/g, '')
       .replace(/football club/g, '')
       .replace(/fc\b/g, '')
       .replace(/cf\b/g, '')
       .replace(/version/g, '')
       .replace(/special/g, '')
       .replace(/casual/g, '')
       .replace(/thick/g, '')
       .replace(/pullover/g, '')
       .replace(/hoodie/g, '')
       .replace(/windbreaker/g, '')
       .replace(/suit/g, '')
       .trim();

  // Remove leading dots again if any appeared after other cleans
  t = t.replace(/^[.\s]+/, '');

  // Check exact match first
  for (const [alias, realName] of Object.entries(TEAM_ALIASES)) {
    if (t === alias) return realName;
  }
  
  // Check includes
  for (const [alias, realName] of Object.entries(TEAM_ALIASES)) {
    // Only match whole words for includes to avoid false positives (e.g. "milan" in some random word)
    const regex = new RegExp(`\\b${alias}\\b`, 'i');
    if (regex.test(t)) {
      return realName;
    }
  }
  
  // If no alias found, clean it up and capitalize
  const cleaned = t.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(' ').trim();
  return cleaned || "Maillot de Football";
}

function parseFolderName(folderName: string) {
  let name = folderName.replace(/^#/, '').trim();
  
  // Clean trailing numbers after sizes like S-XXL3 -> S-XXL
  name = name.replace(/(S-[A-Z0-9XL]+)\d+$/i, '$1');
  
  let season: string | null = null;
  // Match seasons like 23-24, 23/24, 2023-2024, 0103 (01-03), 0304 (03-04), 0506, 0607
  const seasonMatch = name.match(/(20\d{2}[-/]\d{2}|\d{2}[-/]\d{2}|\b\d{4}\b|\b\d{2}\b)/);
  if (seasonMatch) {
    const raw = seasonMatch[1];
    if (raw.length === 4 && !raw.includes('-') && !raw.includes('/')) {
      season = raw.substring(0,2) + '-' + raw.substring(2,4);
    } else if (raw.length === 2) {
      season = '20' + raw; 
    } else {
      season = raw.replace('/', '-');
    }
    name = name.replace(seasonMatch[0], ' ').trim();
  }

  let type = 'Domicile'; // default home
  if (/away|extérieur/i.test(name)) type = 'Extérieur';
  if (/third/i.test(name)) type = 'Third';
  if (/retro|throwback/i.test(name)) type = 'Rétro';
  if (/training|jacket|survetement|veste|pantalon/i.test(name)) type = 'Training';
  if (/goalkeeper|gk|gardien/i.test(name)) type = 'Gardien';
  
  const category = /kids|enfant/i.test(name) || /16#-28#/i.test(name) ? 'Enfant' : 'Adulte';

  // Clean up team name
  let team = name
    .replace(/away|home|third|retro|game|shirt|jersey|long sleeve|short sleeve|jacket|kids|size|edition|domicile|extérieur|third|gardien|throwback|at |kit|player|anniversary|longsleeved/ig, '')
    .replace(/\b[SMLXL0-9#-]+\b/g, '') // remove sizes
    .replace(/[-(),]/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim();

  team = normalizeTeam(team);
  
  if (!team) team = "Maillot de Football";
    
  return { folderName, team, season, type, category };
}

// Global cache for performance
let cachedProducts: Product[] | null = null;

// Fallback products when maillots directory is not available
function getFallbackProducts(): Product[] {
  return [
    {
      id: 'psg-domicile-2024-25',
      name: 'Maillot PSG Domicile 2024-25',
      slug: 'maillot-psg-domicile-2024-25',
      price: 89.99,
      image: '/Images/maillot-psg-domicile-2024-25.jpg',
      hoverImage: undefined,
      images: ['/Images/maillot-psg-domicile-2024-25.jpg'],
      category: 'Adulte',
      team: 'Paris Saint-Germain',
      season: '2024-25',
      type: 'Domicile',
      folderName: 'psg-domicile-2024-25',
      shortDescription: 'Le maillot domicile du PSG pour la saison 2024-25 avec les couleurs emblématiques bleu, rouge et blanc.',
      longDescription: 'Le maillot domicile du PSG pour la saison 2024-25 avec les couleurs emblématiques bleu, rouge et blanc.',
      isNew: true,
      isBestSeller: true,
      badges: ['Nouveau', 'Best-seller']
    },
    {
      id: 'real-madrid-domicile-2024-25',
      name: 'Maillot Real Madrid Domicile 2024-25',
      slug: 'maillot-real-madrid-domicile-2024-25',
      price: 94.99,
      image: '/Images/maillot-real-madrid-domicile-2024-25.jpg',
      hoverImage: undefined,
      images: ['/Images/maillot-real-madrid-domicile-2024-25.jpg'],
      category: 'Adulte',
      team: 'Real Madrid',
      season: '2024-25',
      type: 'Domicile',
      folderName: 'real-madrid-domicile-2024-25',
      shortDescription: 'Le maillot domicile mythique du Real Madrid avec son blanc pur et les détails dorés.',
      longDescription: 'Le maillot domicile mythique du Real Madrid avec son blanc pur et les détails dorés.',
      isNew: true,
      isBestSeller: true,
      badges: ['Nouveau', 'Best-seller']
    },
    {
      id: 'france-domicile-2024-25',
      name: 'Maillot France Domicile 2024-25',
      slug: 'maillot-france-domicile-2024-25',
      price: 92.99,
      image: '/Images/maillot-france-domicile-2024-25.jpg',
      hoverImage: undefined,
      images: ['/Images/maillot-france-domicile-2024-25.jpg'],
      category: 'Adulte',
      team: 'France',
      season: '2024-25',
      type: 'Domicile',
      folderName: 'france-domicile-2024-25',
      shortDescription: 'Le maillot domicile de l\'équipe de France avec le bleu tricolore emblématique.',
      longDescription: 'Le maillot domicile de l\'équipe de France avec le bleu tricolore emblématique.',
      isNew: true,
      isBestSeller: true,
      badges: ['Nouveau', 'Best-seller']
    }
  ];
}

export function getAllProducts(): Product[] {
  if (cachedProducts) return cachedProducts;

  const productsDir = path.join(process.cwd(), 'public', 'maillots');
  
  if (!fs.existsSync(productsDir)) {
    console.warn(`Directory not found: ${productsDir}, using fallback products`);
    return getFallbackProducts();
  }

  const folders = fs.readdirSync(productsDir, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);

  const products: Product[] = [];
  const slugs = new Set<string>();

  for (const folder of folders) {
    const { team, season, type, category } = parseFolderName(folder);
    
    // Construct clean name
    let name = `Maillot ${team}`;
    if (type !== 'Domicile' && type !== 'Rétro' && type !== 'Training') {
      name += ` ${type}`;
    } else if (type === 'Rétro') {
      name = `Maillot Rétro ${team}`;
    } else if (type === 'Training') {
      name = `Survêtement/Training ${team}`;
    }

    if (season) {
      name += ` ${season}`;
    }
    
    if (category === 'Enfant') {
      name += ` (Enfant)`;
    }

    // Generate Slug
    let baseSlug = slugify(`${team} ${type} ${season || ''} ${category === 'Enfant' ? 'enfant' : ''}`, { lower: true, strict: true });
    let slug = baseSlug;
    let counter = 1;
    while (slugs.has(slug)) {
      slug = `${baseSlug}-${counter}`;
      counter++;
    }
    slugs.add(slug);

    // Get images, filtering out invalid ones
    const folderPath = path.join(productsDir, folder);
    const files = fs.readdirSync(folderPath);
    const badImages = getInvalidImages();
    const images = files
      .filter(f => /\.(jpg|jpeg|png|webp|avif)$/i.test(f))
      .map(f => `/maillots/${folder}/${f}`)
      .filter(imgPath => !badImages.has(imgPath));

    if (images.length === 0) continue; // Skip if no valid images

    // Sort images: prefer _1 filename as cover, then natural sort
    images.sort((a, b) => {
      const aIsMain = a.includes('_1.') ? -1 : 0;
      const bIsMain = b.includes('_1.') ? -1 : 0;
      if (aIsMain !== bIsMain) return aIsMain - bIsMain;
      return a.localeCompare(b, undefined, { numeric: true });
    });

    const shortDescription = `Découvrez le ${name.toLowerCase()}. Conçu pour les passionnés, ce modèle offre un confort optimal sur le terrain comme au quotidien.`;
    
    let longDescription = `Affichez fièrement vos couleurs avec ce superbe ${name.toLowerCase()}. Que vous soyez dans les gradins ou sur le terrain, ce modèle allie style et performance.\n\n`;
    longDescription += `- **Équipe :** ${team}\n`;
    if (season) longDescription += `- **Saison :** ${season}\n`;
    longDescription += `- **Type :** ${type}\n`;
    longDescription += `- **Coupe :** Standard\n`;
    longDescription += `- **Qualité :** Tissu respirant et confortable, idéal pour l'effort ou le style streetwear.\n\n`;
    longDescription += `*Attention : La disponibilité des tailles (généralement S à XXL) sera confirmée lors de votre demande de commande.*`;

    products.push({
      id: slug,
      name,
      slug,
      price: 29, // Standard price
      image: images[0],
      hoverImage: images.length > 1 ? images[1] : undefined,
      images,
      category,
      team,
      season,
      type,
      folderName: folder,
      shortDescription,
      longDescription,
      isNew: !season || season.includes('24') || season.includes('25') || season.includes('26'), // basic heuristic for "new"
    });
  }

  // ==========================================
  // DEDUPLICATION
  // Group by normalized name, keep the one with the most images
  // ==========================================
  const deduped = new Map<string, Product>();
  for (const product of products) {
    const key = product.name
      .toLowerCase()
      .trim()
      .replace(/\s+/g, ' ')
      .replace(/[^a-z0-9 ]/g, '');

    const existing = deduped.get(key);
    if (!existing) {
      deduped.set(key, product);
    } else {
      // Keep the one with more images
      if (product.images.length > existing.images.length) {
        deduped.set(key, product);
      }
    }
  }

  const uniqueProducts = Array.from(deduped.values());

  // Sort products: Top Clubs first, then Top Nations, then New, then alphabetical
  uniqueProducts.sort((a, b) => {
    const aIsTopClub = TOP_CLUBS.includes(a.team);
    const bIsTopClub = TOP_CLUBS.includes(b.team);
    if (aIsTopClub && !bIsTopClub) return -1;
    if (!aIsTopClub && bIsTopClub) return 1;

    const aIsTopNation = TOP_NATIONS.includes(a.team);
    const bIsTopNation = TOP_NATIONS.includes(b.team);
    if (aIsTopNation && !bIsTopNation) return -1;
    if (!aIsTopNation && bIsTopNation) return 1;

    // Inside same tier, put newest first
    if (a.isNew && !b.isNew) return -1;
    if (!a.isNew && b.isNew) return 1;

    return a.name.localeCompare(b.name);
  });

  cachedProducts = uniqueProducts;
  return uniqueProducts;
}

export function getProductBySlug(slug: string): Product | undefined {
  const products = getAllProducts();
  return products.find(p => p.slug === slug);
}

export function getProductsByTeam(team: string): Product[] {
  const products = getAllProducts();
  const normalizedTarget = normalizeTeam(team);
  return products.filter(p => p.team === normalizedTarget);
}

export function getProductsByType(type: string): Product[] {
  const products = getAllProducts();
  return products.filter(p => p.type.toLowerCase() === type.toLowerCase());
}
