import fs from 'fs';
import path from 'path';
import slugify from 'slugify';
import { Product } from '@/types';

// Load invalid images list (generated by scripts/filter-bad-images.js)
let invalidImageSet: Set<string> | null = null;
function getInvalidImages(): Set<string> {
  if (!invalidImageSet) {
    try {
      const filePath = path.join(process.cwd(), 'src', 'data', 'invalid-images.json');
      const data = JSON.parse(fs.readFileSync(filePath, 'utf-8')) as string[];
      invalidImageSet = new Set(data);
    } catch {
      invalidImageSet = new Set();
    }
  }
  return invalidImageSet;
}

// ==========================================
// COMPREHENSIVE TEAM ALIASES DICTIONARY
// Maps folder name segments to proper team/nation names
// ==========================================
const TEAM_ALIASES: Record<string, string> = {
  // ---- PREMIER LEAGUE ----
  'man u': 'Manchester United',
  'man utd': 'Manchester United',
  'manchester utd': 'Manchester United',
  'manchester united': 'Manchester United',
  'manchester': 'Manchester United',
  'man city': 'Manchester City',
  'manchester city': 'Manchester City',
  'manchester citys': 'Manchester City',
  'arsenal': 'Arsenal',
  'arsenald': 'Arsenal',
  'chelsea': 'Chelsea',
  'liverpool': 'Liverpool',
  'tottenham': 'Tottenham Hotspur',
  'tottenham hotspur': 'Tottenham Hotspur',
  'aston villa': 'Aston Villa',
  'newcastle': 'Newcastle United',
  'newcastle united': 'Newcastle United',
  'leeds': 'Leeds United',
  'leeds united': 'Leeds United',
  'leicester': 'Leicester City',
  'leicester city': 'Leicester City',
  'everton': 'Everton',
  'evertons': 'Everton',
  'brighton': 'Brighton',
  'brentford': 'Brentford',
  'fulham': 'Fulham',
  'west ham': 'West Ham United',
  'west ham united': 'West Ham United',
  'sunderland': 'Sunderland',
  'sheffield': 'Sheffield United',
  'sheffield wednesday': 'Sheffield Wednesday',
  'sheffield wednesday fc': 'Sheffield Wednesday',

  // ---- LA LIGA ----
  'barca': 'FC Barcelona',
  'barcelona': 'FC Barcelona',
  'barcelonas': 'FC Barcelona',
  'fc barcelona': 'FC Barcelona',
  'real madrid': 'Real Madrid',
  'real madrids': 'Real Madrid',
  'atletico': 'Atlético Madrid',
  'atletico madrid': 'Atlético Madrid',
  'atletico madrids': 'Atlético Madrid',
  'athletic bilbao': 'Athletic Bilbao',
  'betis': 'Real Betis',
  'seville': 'Sevilla FC',
  'sevilla': 'Sevilla FC',
  'sevilla fc': 'Sevilla FC',
  'valencia': 'Valencia CF',
  'villarreal': 'Villarreal CF',
  'girona': 'Girona FC',
  'mallorca': 'RCD Majorque',
  'las palmas': 'UD Las Palmas',
  'la coruna': 'Deportivo La Coruña',
  'levante': 'Levante UD',
  'levante ud': 'Levante UD',
  'sporting de gijon': 'Sporting de Gijón',
  'pisa': 'AC Pisa',

  // ---- SERIE A ----
  'juve': 'Juventus',
  'juventus': 'Juventus',
  'ac milan': 'AC Milan',
  'ac': 'AC Milan',
  'milan': 'AC Milan',
  'inter': 'Inter Milan',
  'inter milan': 'Inter Milan',
  'naples': 'Napoli',
  'napoli': 'Napoli',
  'neapolian': 'Napoli',
  'roma': 'AS Roma',
  'rome': 'AS Roma',
  'romas': 'AS Roma',
  'lazio': 'Lazio',
  'fiorentina': 'Fiorentina',
  'venezia': 'Venezia FC',
  'venezia fc': 'Venezia FC',
  'venice': 'Venezia FC',
  'bologna': 'Bologne FC',
  'atalanta': 'Atalanta',

  // ---- LIGUE 1 ----
  'paris saint germain': 'PSG',
  'paris saintgermain': 'PSG',
  'paris saint germains': 'PSG',
  'paris': 'PSG',
  'psg': 'PSG',
  'ol': 'Olympique Lyonnais',
  'lyon': 'Olympique Lyonnais',
  'lyons': 'Olympique Lyonnais',
  'om': 'Olympique de Marseille',
  'marseille': 'Olympique de Marseille',
  'marseilles': 'Olympique de Marseille',
  'lille': 'LOSC Lille',
  'lens': 'RC Lens',
  'monaco': 'AS Monaco',
  'rennes': 'Stade Rennais',
  'nice': 'OGC Nice',

  // ---- BUNDESLIGA ----
  'bayern': 'Bayern Munich',
  'bayern munich': 'Bayern Munich',
  'bvb': 'Borussia Dortmund',
  'dortmund': 'Borussia Dortmund',
  'borussia dortmund': 'Borussia Dortmund',
  'leverkusen': 'Bayer Leverkusen',
  'bayer leverkusen': 'Bayer Leverkusen',
  'leipzig': 'RB Leipzig',
  'mainz': 'Mayence 05',
  'hamburg': 'Hambourg SV',
  'frankfurt': 'Eintracht Francfort',
  'nuremberg': 'FC Nuremberg',
  'borussia monchengladbach': 'Borussia Mönchengladbach',

  // ---- EREDIVISIE ----
  'ajax': 'Ajax Amsterdam',
  'ajaxs': 'Ajax Amsterdam',
  'psv': 'PSV Eindhoven',
  'psv eindhoven': 'PSV Eindhoven',
  'feyenoord': 'Feyenoord',

  // ---- PORTUGAL ----
  'benfica': 'SL Benfica',
  'benficas': 'SL Benfica',
  'porto': 'FC Porto',
  'sporting': 'Sporting CP',
  'sporting cp': 'Sporting CP',

  // ---- SCOTLAND ----
  'celtic': 'Celtic FC',
  'celtics': 'Celtic FC',
  'rangers': 'Rangers FC',
  'rangers football': 'Rangers FC',
  'rangers football club': 'Rangers FC',
  'scotland': 'Écosse',

  // ---- TURKEY ----
  'galatasaray': 'Galatasaray',
  'galatasaray sk': 'Galatasaray',
  'fenerbahce': 'Fenerbahçe',
  'besiktas': 'Beşiktaş',
  'besiktas jk': 'Beşiktaş',

  // ---- SOUTH AMERICA ----
  'boca': 'Boca Juniors',
  'boca juniors': 'Boca Juniors',
  'river plate': 'River Plate',
  'flamengo': 'Flamengo',
  'flamenco': 'Flamengo',
  'corinthians': 'Corinthians',
  'palmeiras': 'Palmeiras',
  'palmelas': 'Palmeiras',
  'santos': 'Santos FC',
  'sao paulo': 'São Paulo',
  'sao paulos': 'São Paulo',
  'fluminense': 'Fluminense',
  'fruimense': 'Fluminense',
  'cruzeiro': 'Cruzeiro',
  'cruisersro': 'Cruzeiro',
  'botafogo': 'Botafogo',
  'botafogo rj': 'Botafogo',
  'botagago': 'Botafogo',
  'vasco da gama': 'Vasco da Gama',
  'vasco da gama rj': 'Vasco da Gama',
  'club de regatas vasco da gama': 'Vasco da Gama',
  'clube atletico mineiro': 'Atlético Mineiro',
  'colocolo': 'Colo-Colo',

  // ---- NORTH / CENTRAL AMERICA ----
  'miami': 'Inter Miami',
  'miami international': 'Inter Miami',
  'inter miami': 'Inter Miami',
  'la galaxy': 'LA Galaxy',
  'galaxy': 'LA Galaxy',
  'los angeles': 'LA Galaxy',
  'new york red bulls': 'New York Red Bulls',
  'york red bulls': 'New York Red Bulls',
  'blue cross': 'Cruz Azul',
  'chivas': 'Chivas Guadalajara',
  'chivas guadalajara': 'Chivas Guadalajara',
  'chivas guadalajara cd': 'Chivas Guadalajara',
  'americas': 'Club América',
  'american': 'Club América',
  'pumas unam': 'Pumas UANL',
  'toluca': 'Deportivo Toluca',
  'tigers': 'Tigres UANL',

  // ---- MIDDLE EAST ----
  'al nassr': 'Al Nassr FC',
  'al nassr fc': 'Al Nassr FC',
  'al hilal': 'Al Hilal',
  'al ahli': 'Al Ahli',
  'al ahly jeddah': 'Al Ahli Jeddah',
  'al ain': 'Al Ain FC',
  'al ain fc': 'Al Ain FC',
  'riad crescent': 'Al Hilal',
  'riyadh': 'Al Riyadh',
  'riyadh victory': 'Al Nassr FC',
  'riyadh win': 'Al Nassr FC',
  'moon of riyadh': 'Al Hilal',
  'saudi arabia jeddah': 'Al Ittihad Jeddah',
  'jeddah united': 'Al Ittihad Jeddah',
  'johor': 'Johor Darul Ta\'zim',

  // ---- OTHER CLUBS ----
  'red bull salzburg': 'Red Bull Salzbourg',
  'austrian red bull': 'Red Bull Salzbourg',
  'austria': 'Autriche',
  'hongjia olympia': 'Olympia FC',
  'guoan': 'Beijing Guoan',
  'victoria': 'CF Victoria',
  'kings league santos': 'Santos FC',
  'shining': 'Shining FC',
  'oasis band': 'Manchester City',

  // ---- NATIONAL TEAMS ----
  'france': 'France',
  'french': 'France',
  'frances': 'France',
  'argentina': 'Argentine',
  'argentine': 'Argentine',
  'argentinas': 'Argentine',
  'brazil': 'Brésil',
  'brazilian': 'Brésil',
  'brazils': 'Brésil',
  'germany': 'Allemagne',
  'german': 'Allemagne',
  'spain': 'Espagne',
  'spanish': 'Espagne',
  'italy': 'Italie',
  'italian': 'Italie',
  'england': 'Angleterre',
  'english': 'Angleterre',
  'englands': 'Angleterre',
  'portugal': 'Portugal',
  'portuguese': 'Portugal',
  'netherlands': 'Pays-Bas',
  'nederlanden': 'Pays-Bas',
  'dutch': 'Pays-Bas',
  'belgium': 'Belgique',
  'belgian': 'Belgique',
  'morocco': 'Maroc',
  'moroccan': 'Maroc',
  'algeria': 'Algérie',
  'algerian': 'Algérie',
  'algier': 'Algérie',
  'senegal': 'Sénégal',
  'cameroon': 'Cameroun',
  'cameroun': 'Cameroun',
  'ivory coast': 'Côte d\'Ivoire',
  'cote divoire': 'Côte d\'Ivoire',
  'japan': 'Japon',
  'japanese': 'Japon',
  'mexico': 'Mexique',
  'mexican': 'Mexique',
  'colombia': 'Colombie',
  'colombian': 'Colombie',
  'columbia': 'Colombie',
  'uruguay': 'Uruguay',
  'chile': 'Chili',
  'croatia': 'Croatie',
  'ireland': 'Irlande',
  'irish': 'Irlande',
  'northern ireland': 'Irlande du Nord',
  'wales': 'Pays de Galles',
  'south korea': 'Corée du Sud',
  'nigeria': 'Nigeria',
  'mali': 'Mali',
  'ghana': 'Ghana',
  'palestine': 'Palestine',
  'palestinian': 'Palestine',
  'us': 'États-Unis',
  'usa': 'États-Unis',
  'canada': 'Canada',
  'canadian': 'Canada',
  'china': 'Chine',
  'saudi arabia': 'Arabie Saoudite',
  'venezuela': 'Venezuela',
  'jamaica': 'Jamaïque',
};

export const TOP_CLUBS = [
  'Real Madrid', 'FC Barcelona', 'PSG', 'Manchester City', 'Arsenal', 
  'Manchester United', 'Liverpool', 'Chelsea', 'Bayern Munich', 
  'Juventus', 'AC Milan', 'Inter Milan', 'Atlético Madrid', 'Borussia Dortmund',
  'Olympique de Marseille', 'Olympique Lyonnais', 'Napoli', 'AS Roma',
  'Tottenham Hotspur', 'Newcastle United'
];

export const TOP_NATIONS = [
  'France', 'Argentine', 'Brésil', 'Allemagne', 'Espagne', 
  'Italie', 'Angleterre', 'Portugal', 'Maroc', 'Algérie', 'Sénégal',
  'Pays-Bas', 'Belgique', 'Croatie'
];

// ==========================================
// FOLDER NAME PARSER
// Converts hyphenated folder names into structured product data
// ==========================================

// Words to strip when extracting team name
const NOISE_WORDS = new Set([
  'home', 'away', 'third', 'retro', 'game', 'games', 'shirt', 'jersey',
  'long', 'sleeve', 'short', 'sleeved', 'goalkeeper', 'gk',
  'player', 'players', 'version', 'edition', 'at',
  'throwback', 'windbreaker', 'suit', 'size', 'sizes',
  'special', 'anniversary', 'court', 'limited', 'commemorative',
  'commemorates', 'casual', 'concept', 'concepts', 'graffiti', 'set',
  'promo', 'promotion', 'kit', 'team', 'pre', 'match', 'uniform',
  'womens', 'women', 'womeninter', 'new', 'champion', 'champions',
  'vest', 'blouse', 'dress', 'clothing', 'style', 'tank', 'top',
  'collaboration', 'poio', 'po', 'collection', 'coat', 'trench',
  'grey', 'gray', 'black', 'white', 'blue', 'red', 'green', 'yellow',
  'pink', 'purple', 'orange', 'beige', 'maroon', 'fluorescent',
  'dark', 'light', 'grayish', 'gradient', 'golden',
  'fabric', 'outfit', 'advertisement', 'derby', 'ads', 'ad',
  'without', 'with', 'behind', 'of', 'the', 'in', 'for', 'is', 'a',
  'cup', 'nations', 'africa', 'world', 'fifa', 'qatar', 'uefa',
  'beer', 'oktoberfest', 'halloween', 'wonder', 'woman', 'star',
  'basketball', 'dragon', 'chinese', 'jet', 'bull', 'man',
  'peach', 'collar', 'round', 'lap', 'lapel', 'reflective',
  'combined', 'design', 'love', 'ovo', 'drake', 'karol', 'rosala',
  'graffiti', 'board', 'camp', 'nou', 'lv', 'cobrand', 'cobranded',
  'brazil', 'gold', 'golden', 'headman', 'yuan', 'joint',
  'camouflage', 'double', 'sided', 'patchwork',
  'tap', 'treble', 'winner', 'winners', 'final', 'finals',
  'sweats', 'sweatshirt', 'outfits',
  'leaf', 'parrot', 'lake', 'rose', 'bamboo', 'goddess', 'mary', 'brown',
  'guest', 'three', 'october',
  'classic', 'vintage', 'centenary', 'bundesliga', 'cold',
  'half', 'tops', 'fourth', '125th', '10th', '50th', '25th', '120th', 
  '1901', '2nd', '9th',
  'international', 'national', 'anime',
  'hoodie', 'pullover', 'thick', 'stadium',
  'patch', 'no', 'label',
  'shining', 'hongjia', 'olympia', 'victoria',
  'kings', 'league', 'oasis', 'band',
  's4xl', 'sxxl', 's2xl', 's3xl', 's4xxl',
]);

function normalizeTeamFromTokens(tokens: string[]): string {
  // Join tokens into a string for matching
  const joined = tokens.join(' ').toLowerCase().trim();
  
  if (!joined) return 'Maillot de Football';

  // Try exact match on the full joined string
  if (TEAM_ALIASES[joined]) return TEAM_ALIASES[joined];

  // Try progressively smaller windows (longest match first)
  for (let windowSize = Math.min(tokens.length, 5); windowSize >= 1; windowSize--) {
    for (let i = 0; i <= tokens.length - windowSize; i++) {
      const window = tokens.slice(i, i + windowSize).join(' ').toLowerCase();
      if (TEAM_ALIASES[window]) return TEAM_ALIASES[window];
    }
  }

  // Try individual tokens
  for (const token of tokens) {
    const t = token.toLowerCase();
    if (TEAM_ALIASES[t]) return TEAM_ALIASES[t];
  }

  // If we still can't find a match, capitalize each token
  const capitalized = tokens
    .filter(t => t.length > 0)
    .map(t => t.charAt(0).toUpperCase() + t.slice(1).toLowerCase())
    .join(' ')
    .trim();

  return capitalized || 'Maillot de Football';
}

function parseFolderName(folderName: string) {
  // Skip junk folders (HTTP URLs from scraping)
  if (folderName.startsWith('http')) {
    return { folderName, team: 'Autres', season: null, type: 'Domicile', category: 'Adulte' };
  }

  let name = folderName.replace(/^#/, '').trim();

  // ---- STEP 1: Extract season ----
  let season: string | null = null;

  // Remove trailing size patterns first: -s-xxl7, -s-4xl3, -s-2xl6, -16-283, -s-4xxl12
  name = name.replace(/-s-\d*x+l\d*$/i, '');
  name = name.replace(/-s-\d+xl\d*$/i, '');
  name = name.replace(/-s-\d*xxl?\d*$/i, '');
  name = name.replace(/-s4xl\d*$/i, '');
  name = name.replace(/-16-\d+$/i, '');
  name = name.replace(/-\d+xl\d*$/i, ''); // catches leftover size suffixes
  // Remove trailing lone numbers (image index or size residuals)
  name = name.replace(/\d+$/, '');
  name = name.replace(/-+$/, '');

  // Extract leading season: patterns like 2526-, 0304-, 2324-, 9798-, 199800-, 198990-, 2019-20-
  // Format A: 4 digit contiguous like 2526, 0304
  const leadingSeasonA = name.match(/^(\d{4})-/);
  // Format B: 6 digit like 199800, 198990
  const leadingSeasonB = name.match(/^(\d{6})-/);
  // Format C: YYYY-YY like 2019-20, 1990-92
  const leadingSeasonC = name.match(/^(\d{4})-(\d{2})-/);
  // Format D: 2 digit like 04-
  const leadingSeasonD = name.match(/^(\d{2})-(\d{2})-/);
  // Format E: just 2 digits leading
  const leadingSeasonE = name.match(/^(\d{2})-(?!\d)/);

  if (leadingSeasonC) {
    // e.g., 2019-20 -> 19-20
    season = leadingSeasonC[1].slice(2) + '-' + leadingSeasonC[2];
    name = name.slice(leadingSeasonC[0].length);
  } else if (leadingSeasonB) {
    // e.g., 199800 -> 98-00, 198990 -> 89-90
    const raw = leadingSeasonB[1];
    season = raw.slice(2, 4) + '-' + raw.slice(4, 6);
    name = name.slice(leadingSeasonB[0].length);
  } else if (leadingSeasonD) {
    // Check if this looks like a 2-digit + 2-digit season (07-08)
    const a = parseInt(leadingSeasonD[1]);
    const b = parseInt(leadingSeasonD[2]);
    if (b === a + 1 || (a === 99 && b === 0)) {
      season = leadingSeasonD[1] + '-' + leadingSeasonD[2];
      name = name.slice(leadingSeasonD[0].length);
    }
  } else if (leadingSeasonA) {
    const raw = leadingSeasonA[1];
    const first = parseInt(raw.slice(0, 2));
    const second = parseInt(raw.slice(2, 4));
    // Filter out actual years like 1892, 1974, 1984, 1990, 1994, 1995, 1996, 1997, 1998, 2000, 2001, etc.
    if (first >= 19 && first <= 30 && (second === first + 1 || (first === 99 && second === 0) || second === first)) {
      // It's a season like 2526, 2324, 2627
      season = raw.slice(0, 2) + '-' + raw.slice(2, 4);
      name = name.slice(leadingSeasonA[0].length);
    } else if (parseInt(raw) >= 1890 && parseInt(raw) <= 2030) {
      // It's a year like 1892, 1974, 1998, 2000 - extract as approximate season
      const yearNum = parseInt(raw);
      if (yearNum < 100) {
        season = raw.padStart(2, '0');
      } else {
        const shortYear = raw.slice(2);
        season = shortYear;
      }
      name = name.slice(leadingSeasonA[0].length);
    } else {
      // Treat as season digits
      season = raw.slice(0, 2) + '-' + raw.slice(2, 4);
      name = name.slice(leadingSeasonA[0].length);
    }
  } else if (leadingSeasonE) {
    // Just 2 leading digits like 04-
    const num = parseInt(leadingSeasonE[1]);
    if (num >= 0 && num <= 30) {
      season = '20' + leadingSeasonE[1];
      name = name.slice(leadingSeasonE[0].length);
    }
  }

  // Also check for season elsewhere: "world-cup-2022", "season-199596"
  if (!season) {
    const inlineSeason = name.match(/(\d{4})(?=-|$)/);
    if (inlineSeason) {
      const yr = parseInt(inlineSeason[1]);
      if (yr >= 1970 && yr <= 2030) {
        season = inlineSeason[1].slice(2);
        name = name.replace(inlineSeason[0], '');
      }
    }
  }

  // Normalize season display: make seasons like '20' show as '20-21' etc. 
  // But keep single years  like '98', '04' as-is for retro
  if (season && season.length === 2) {
    // Single year - keep as 20XX for recent, or just the year for retro
    const num = parseInt(season);
    if (num >= 0 && num <= 30) {
      season = '20' + season;
    }
  }

  // ---- STEP 2: Detect type ----
  let type = 'Domicile';
  const nameLower = name.toLowerCase();
  
  if (/\baway\b/.test(nameLower) || /\bexterieur\b/.test(nameLower) || /\bextérieur\b/.test(nameLower)) type = 'Extérieur';
  if (/\bthird\b/.test(nameLower)) type = 'Third';
  if (/\bretro\b/.test(nameLower) || /\bthrowback\b/.test(nameLower)) type = 'Rétro';
  if (/\btraining\b/.test(nameLower) || /\bwindbreaker\b/.test(nameLower) || /\bsuit\b/.test(nameLower) || /\bjacket\b/.test(nameLower) || /\bhoodie\b/.test(nameLower) || /\bcoat\b/.test(nameLower) || /\bsweats/i.test(nameLower) || /\bpullover\b/.test(nameLower) || /\bpromotion\b/.test(nameLower)) type = 'Training';
  if (/\bgoalkeeper\b/.test(nameLower) || /\bgardien\b/.test(nameLower) || /\bgk\b/.test(nameLower)) type = 'Gardien';

  // ---- STEP 3: Detect category and flags ----
  const isKids = /\bkids?\b/.test(nameLower) || /\benfant\b/.test(nameLower) || /\b16-28\b/.test(name);
  const isWomens = /\bwomens?\b/.test(nameLower) || /\bwomeninter\b/.test(nameLower) || /\bblouse\b/.test(nameLower) || /\bvest\b/.test(nameLower) || /\btank.top\b/.test(nameLower) || /\bdress\b/.test(nameLower);
  const isPlayerEdition = /\bplayer\b/.test(nameLower) || /\bplayers\b/.test(nameLower);
  const category = isKids ? 'Enfant' : 'Adulte';

  // ---- STEP 4: Extract team name ----
  // Tokenize on hyphens
  const rawTokens = name.split('-').map(t => t.trim()).filter(t => t.length > 0);
  
  // Remove noise words and keep team-relevant tokens
  const teamTokens: string[] = [];
  for (const token of rawTokens) {
    const lower = token.toLowerCase();
    // Skip noise words, pure numbers, size patterns
    if (NOISE_WORDS.has(lower)) continue;
    if (/^\d+$/.test(token)) continue;
    if (/^s?\d*x+l\d*$/i.test(token)) continue;
    if (/^[sml]$/i.test(token)) continue;
    // Remove trailing 's' that indicates possessive (barcelonas -> barcelona)
    // But keep if token is too short or is a known alias with s
    teamTokens.push(token);
  }

  const team = normalizeTeamFromTokens(teamTokens);

  return { folderName, team, season, type, category, isWomens, isPlayerEdition, isKids };
}

// Global cache for performance
let cachedProducts: Product[] | null = null;

// Process products from JSON catalog
function processProductsFromCatalog(catalogData: Array<{folderName: string, images: string[]}>): Product[] {
  const products: Product[] = [];
  const slugs = new Set<string>();

  for (const item of catalogData) {
    const { folderName: folder, images: rawImages } = item;
    const parsed = parseFolderName(folder);
    const { team, season, type, category } = parsed;
    const isWomens = parsed.isWomens || false;
    const isPlayerEdition = parsed.isPlayerEdition || false;
    
    // Skip junk folders
    if (team === 'Autres' || team === 'Maillot de Football') continue;
    
    // Encode images from catalog
    const images = rawImages;
    
    // Construct clean professional name
    let name = '';
    if (type === 'Rétro') {
      name = `Maillot Rétro ${team}`;
    } else if (type === 'Training') {
      name = `Training ${team}`;
    } else if (type === 'Gardien') {
      name = `Maillot ${team} Gardien`;
    } else if (type === 'Extérieur') {
      name = `Maillot ${team} Extérieur`;
    } else if (type === 'Third') {
      name = `Maillot ${team} Third`;
    } else {
      name = `Maillot ${team}`;
    }

    if (season) {
      name += ` ${season}`;
    }
    
    if (isPlayerEdition) {
      name += ` Player Edition`;
    }
    
    if (isWomens) {
      name += ` (Femme)`;
    }
    
    if (category === 'Enfant') {
      name += ` (Enfant)`;
    }

    // Generate Slug
    let baseSlug = slugify(`${team} ${type} ${season || ''} ${isPlayerEdition ? 'player' : ''} ${isWomens ? 'femme' : ''} ${category === 'Enfant' ? 'enfant' : ''}`, { lower: true, strict: true });
    let slug = baseSlug;
    let counter = 1;
    while (slugs.has(slug)) {
      slug = `${baseSlug}-${counter}`;
      counter++;
    }
    slugs.add(slug);

    if (images.length === 0) continue;

    const price = isPlayerEdition ? 34 : 29;
    
    const shortDescription = isPlayerEdition
      ? `Achetez le ${name} au meilleur prix sur KIT FOOTBALL. Maillot haute performance, coupe ajustée, tissu premium ultra-respirant. Livraison express 48h.`
      : `Commandez votre ${name} pas cher (${price}€) sur KIT FOOTBALL. Maillot de foot haute qualité, idéal pour le terrain ou les supporters. Stock limité, livraison rapide.`;
    
    let longDescription = isPlayerEdition
      ? `### Version Player Edition - Qualité Professionnelle\n\nPropulsez votre jeu au niveau supérieur avec le **${name}**. Ce maillot est la réplique exacte de celui porté par les joueurs sur le terrain.\n\n`
      : `### ${name} - Édition Supporter\n\nAffichez votre passion pour votre équipe avec le **${name}**. Conçu pour allier confort et style, ce maillot est parfait pour toutes les occasions.\n\n`;
    
    longDescription += `#### Caractéristiques techniques :\n`;
    longDescription += `- **Équipe :** ${team}\n`;
    if (season) longDescription += `- **Saison :** ${season}\n`;
    longDescription += `- **Type :** ${type}\n`;
    longDescription += isPlayerEdition ? `- **Version :** Player Edition (Coupe athlétique ajustée)\n` : `- **Version :** Fan Edition (Coupe standard confortable)\n`;
    longDescription += `- **Tissu :** Technologie respirante pour une évacuation optimale de la transpiration\n`;
    longDescription += `- **Détails :** Logos brodés (Fan) ou thermocollés (Player) selon la version\n\n`;
    longDescription += `#### Pourquoi acheter sur KIT FOOTBALL ?\n`;
    longDescription += `- **Prix imbattable :** Votre maillot de foot à partir de 29€.\n`;
    longDescription += `- **Qualité Premium :** Finitions soignées et matériaux durables.\n`;
    longDescription += `- **Livraison Rapide :** Expédition sous 48h avec suivi.\n`;
    longDescription += `- **Satisfaction Garantie :** Service client réactif à votre écoute.\n\n`;
    longDescription += `*Disponible en tailles S, M, L, XL, XXL. Profitez-en avant la rupture de stock !*`;

    const isNew = !season || season.includes('24') || season.includes('25') || season.includes('26');
    const isBestSeller = TOP_CLUBS.includes(team) || TOP_NATIONS.includes(team);
    
    const keywords = [
      `maillot ${team}`,
      `maillot ${team} ${season || ''}`.trim(),
      `maillot ${team} ${type}`,
      `maillot foot ${team} pas cher`,
      `achat maillot ${team}`,
      `boutique ${team}`,
      `kit football ${team}`
    ].filter(k => k.trim().length > 0);

    const badges: string[] = [];
    if (isNew) badges.push('Nouveau');
    if (isBestSeller) badges.push('Best-seller');
    if (isPlayerEdition) badges.push('Player Edition');

    products.push({
      id: slug,
      name,
      slug,
      price,
      image: images[0],
      hoverImage: images.length > 1 ? images[1] : undefined,
      images,
      category,
      team,
      season,
      type,
      folderName: folder,
      shortDescription,
      longDescription,
      isNew,
      isBestSeller,
      badges: badges.length > 0 ? badges : undefined,
      keywords
    });
  }

  // ==========================================
  // DEDUPLICATION
  // Use folderName as key to show all 1000 maillots
  // ==========================================
  const deduped = new Map<string, Product>();
  for (const product of products) {
    const key = product.folderName;

    const existing = deduped.get(key);
    if (!existing) {
      deduped.set(key, product);
    }
  }

  const uniqueProducts = Array.from(deduped.values());

  // Sort products
  uniqueProducts.sort((a, b) => {
    const aIsTopClub = TOP_CLUBS.includes(a.team);
    const bIsTopClub = TOP_CLUBS.includes(b.team);
    if (aIsTopClub && !bIsTopClub) return -1;
    if (!aIsTopClub && bIsTopClub) return 1;

    const aIsTopNation = TOP_NATIONS.includes(a.team);
    const bIsTopNation = TOP_NATIONS.includes(b.team);
    if (aIsTopNation && !bIsTopNation) return -1;
    if (!aIsTopNation && bIsTopNation) return 1;

    if (a.isNew && !b.isNew) return -1;
    if (!a.isNew && b.isNew) return 1;

    return a.name.localeCompare(b.name);
  });

  cachedProducts = uniqueProducts;
  return uniqueProducts;
}

// Fallback products when maillots directory is not available - 100 best-selling jerseys
function getFallbackProducts(): Product[] {
  const topJerseys = [
    // Top Clubs - Domicile 2024-25
    { team: 'Real Madrid', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Real Madrid', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'FC Barcelona', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'FC Barcelona', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'PSG', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'PSG', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Manchester City', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Manchester City', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Arsenal', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Arsenal', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Liverpool', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Liverpool', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Manchester United', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Manchester United', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Bayern Munich', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Bayern Munich', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Inter Milan', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Inter Milan', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'AC Milan', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'AC Milan', type: 'Domicile', season: '24-25', isPlayer: true },
    
    // Top Clubs - Extérieur 2024-25
    { team: 'Real Madrid', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'FC Barcelona', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'PSG', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'Manchester City', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'Arsenal', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'Liverpool', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'Chelsea', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Chelsea', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'Juventus', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Juventus', type: 'Extérieur', season: '24-25', isPlayer: false },
    
    // National Teams 2024-25
    { team: 'France', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'France', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'France', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'Argentine', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Argentine', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Brésil', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Brésil', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Allemagne', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Espagne', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Espagne', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Portugal', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Portugal', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Angleterre', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Italie', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Pays-Bas', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Belgique', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Maroc', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Maroc', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Algérie', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Sénégal', type: 'Domicile', season: '24-25', isPlayer: false },
    
    // More Top Clubs
    { team: 'Atletico Madrid', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Borussia Dortmund', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Borussia Dortmund', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Napoli', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'AS Roma', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Tottenham Hotspur', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Newcastle United', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Olympique de Marseille', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Olympique Lyonnais', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'AS Monaco', type: 'Domicile', season: '24-25', isPlayer: false },
    
    // Retro Classics
    { team: 'Real Madrid', type: 'Rétro', season: '13-14', isPlayer: false },
    { team: 'FC Barcelona', type: 'Rétro', season: '10-11', isPlayer: false },
    { team: 'Manchester United', type: 'Rétro', season: '07-08', isPlayer: false },
    { team: 'AC Milan', type: 'Rétro', season: '06-07', isPlayer: false },
    { team: 'Arsenal', type: 'Rétro', season: '03-04', isPlayer: false },
    { team: 'France', type: 'Rétro', season: '98', isPlayer: false },
    { team: 'Brésil', type: 'Rétro', season: '02', isPlayer: false },
    { team: 'Argentine', type: 'Rétro', season: '86', isPlayer: false },
    
    // Third Kits
    { team: 'Real Madrid', type: 'Third', season: '24-25', isPlayer: false },
    { team: 'FC Barcelona', type: 'Third', season: '24-25', isPlayer: false },
    { team: 'PSG', type: 'Third', season: '24-25', isPlayer: false },
    { team: 'Manchester City', type: 'Third', season: '24-25', isPlayer: false },
    { team: 'Bayern Munich', type: 'Third', season: '24-25', isPlayer: false },
    
    // More Clubs
    { team: 'Benfica', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'FC Porto', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Sporting CP', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Ajax Amsterdam', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'PSV Eindhoven', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Celtic FC', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Rangers FC', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Galatasaray', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Fenerbahce', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Inter Miami', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Inter Miami', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Al Nassr', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Al Nassr', type: 'Domicile', season: '24-25', isPlayer: true },
    
    // More National Teams
    { team: 'Cameroun', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Côte d\'Ivoire', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Mexique', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Colombie', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Uruguay', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Japon', type: 'Domicile', season: '24-25', isPlayer: false },
    
    // Additional Popular Clubs
    { team: 'Aston Villa', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Leicester City', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Sevilla', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Valencia', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Lazio', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Fiorentina', type: 'Domicile', season: '24-25', isPlayer: false },
  ];

  return topJerseys.map((jersey, index) => {
    const price = jersey.isPlayer ? 34 : 29;
    const playerSuffix = jersey.isPlayer ? ' Player Edition' : '';
    const name = `Maillot ${jersey.team} ${jersey.type} ${jersey.season}${playerSuffix}`;
    const slug = slugify(name, { lower: true, strict: true });
    const id = `${slug}-${index}`;
    
    const shortDescription = jersey.isPlayer 
      ? `Version Player Edition du ${name.toLowerCase()}. Qualité professionnelle, coupe athlétique, tissu technique premium.`
      : `Découvrez le ${name.toLowerCase()}. Conçu pour les passionnés, ce modèle offre un confort optimal sur le terrain comme au quotidien.`;
    
    let longDescription = jersey.isPlayer
      ? `Version Player Edition authentique du ${name.toLowerCase()}. Identique aux maillots portés par les joueurs professionnels.\n\n`
      : `Affichez fièrement vos couleurs avec ce superbe ${name.toLowerCase()}. Que vous soyez dans les gradins ou sur le terrain, ce modèle allie style et performance.\n\n`;
    
    longDescription += `- **Équipe :** ${jersey.team}\n`;
    longDescription += `- **Saison :** ${jersey.season}\n`;
    longDescription += `- **Type :** ${jersey.type}\n`;
    longDescription += jersey.isPlayer ? `- **Version :** Player Edition (Qualité Pro)\n` : `- **Version :** Fan Edition\n`;
    longDescription += `- **Coupe :** ${jersey.isPlayer ? 'Athlétique ajustée' : 'Standard confortable'}\n`;
    longDescription += `- **Qualité :** ${jersey.isPlayer ? 'Tissu technique premium, ultra-respirant' : 'Tissu respirant et confortable'}\n\n`;
    longDescription += `*Tailles disponibles : S, M, L, XL, XXL. Livraison rapide 48h.*`;

    const isNew = jersey.season.includes('24') || jersey.season.includes('25');
    const isBestSeller = !jersey.isPlayer && ['Real Madrid', 'FC Barcelona', 'PSG', 'France', 'Argentine', 'Manchester City'].includes(jersey.team);

    const badges: string[] = [];
    if (isNew) badges.push('Nouveau');
    if (isBestSeller) badges.push('Best-seller');
    if (jersey.isPlayer) badges.push('Player Edition');

    return {
      id,
      name,
      slug,
      price,
      image: '/Images/maillot-psg-domicile-2024-25.jpg', // Placeholder
      hoverImage: undefined,
      images: ['/Images/maillot-psg-domicile-2024-25.jpg'],
      category: 'Adulte',
      team: jersey.team,
      season: jersey.season,
      type: jersey.type,
      folderName: slug,
      shortDescription,
      longDescription,
      isNew,
      isBestSeller,
      badges: badges.length > 0 ? badges : undefined
    };
  });
}

export function getAllProducts(): Product[] {
  if (cachedProducts) return cachedProducts;

  const productsDir = path.join(process.cwd(), 'public', 'maillots');
  
  // Try to load from JSON catalog if directory doesn't exist
  if (!fs.existsSync(productsDir)) {
    console.warn(`Directory not found: ${productsDir}, trying JSON catalog`);
    try {
      const catalogPath = path.join(process.cwd(), 'src', 'data', 'maillots-catalog.json');
      if (fs.existsSync(catalogPath)) {
        const catalogData = JSON.parse(fs.readFileSync(catalogPath, 'utf-8'));
        return processProductsFromCatalog(catalogData);
      }
    } catch (error) {
      console.error('Error loading catalog:', error);
    }
    console.warn('JSON catalog not found, using fallback products');
    return getFallbackProducts();
  }

  const folders = fs.readdirSync(productsDir, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);

  const products: Product[] = [];
  const slugs = new Set<string>();

  for (const folder of folders) {
    const { team, season, type, category } = parseFolderName(folder);
    
    // Construct clean name
    let name = `Maillot ${team}`;
    if (type !== 'Domicile' && type !== 'Rétro' && type !== 'Training') {
      name += ` ${type}`;
    } else if (type === 'Rétro') {
      name = `Maillot Rétro ${team}`;
    } else if (type === 'Training') {
      name = `Survêtement/Training ${team}`;
    }

    if (season) {
      name += ` ${season}`;
    }
    
    if (category === 'Enfant') {
      name += ` (Enfant)`;
    }

    // Generate Slug
    let baseSlug = slugify(`${team} ${type} ${season || ''} ${category === 'Enfant' ? 'enfant' : ''}`, { lower: true, strict: true });
    let slug = baseSlug;
    let counter = 1;
    while (slugs.has(slug)) {
      slug = `${baseSlug}-${counter}`;
      counter++;
    }
    slugs.add(slug);

    // Get images, filtering out invalid ones
    const folderPath = path.join(productsDir, folder);
    const files = fs.readdirSync(folderPath);
    const badImages = getInvalidImages();
    const images = files
      .filter(f => /\.(jpg|jpeg|png|webp|avif)$/i.test(f))
      .map(f => `/maillots/${folder}/${f}`)
      .filter(imgPath => !badImages.has(imgPath));

    if (images.length === 0) continue; // Skip if no valid images

    // Sort images: prefer _1 filename as cover, then natural sort
    images.sort((a, b) => {
      const aIsMain = a.includes('_1.') ? -1 : 0;
      const bIsMain = b.includes('_1.') ? -1 : 0;
      if (aIsMain !== bIsMain) return aIsMain - bIsMain;
      return a.localeCompare(b, undefined, { numeric: true });
    });

    // Detect Player Edition for pricing
    const isPlayerEdition = /player|edition/i.test(folder);
    const price = isPlayerEdition ? 34 : 29;
    
    const shortDescription = isPlayerEdition
      ? `Achetez le ${name} (Version Player) au meilleur prix sur KIT FOOTBALL. Maillot haute performance, coupe ajustée, tissu premium ultra-respirant. Livraison express 48h.`
      : `Commandez votre ${name} pas cher (29€) sur KIT FOOTBALL. Maillot de foot haute qualité, idéal pour le terrain ou les supporters. Stock limité, livraison rapide.`;
    
    let longDescription = isPlayerEdition
      ? `### Version Player Edition - Qualité Professionnelle\n\nPropulsez votre jeu au niveau supérieur avec le **${name} Version Player**. Ce maillot est la réplique exacte de celui porté par les joueurs sur le terrain.\n\n`
      : `### Maillot ${name} - Édition Supporter\n\nAffichez votre passion pour votre équipe avec le **${name}**. Conçu pour allier confort et style, ce maillot est parfait pour toutes les occasions.\n\n`;
    
    longDescription += `#### Caractéristiques techniques :\n`;
    longDescription += `- **Équipe officielle :** ${team}\n`;
    if (season) longDescription += `- **Saison :** ${season}\n`;
    longDescription += `- **Type de maillot :** ${type}\n`;
    longDescription += isPlayerEdition ? `- **Version :** Player Edition (Coupe athlétique ajustée)\n` : `- **Version :** Fan Edition (Coupe standard confortable)\n`;
    longDescription += `- **Tissu :** Technologie respirante pour une évacuation optimale de la transpiration\n`;
    longDescription += `- **Détails :** Logos brodés (Fan) ou thermocollés (Player) selon la version\n\n`;
    longDescription += `#### Pourquoi acheter sur KIT FOOTBALL ?\n`;
    longDescription += `- **Prix imbattable :** Votre maillot de foot à partir de 29€.\n`;
    longDescription += `- **Qualité Premium :** Finitions soignées et matériaux durables.\n`;
    longDescription += `- **Livraison Rapide :** Expédition sous 48h avec suivi.\n`;
    longDescription += `- **Satisfaction Garantie :** Service client réactif à votre écoute.\n\n`;
    longDescription += `*Disponible en tailles S, M, L, XL, XXL. Profitez-en avant la rupture de stock !*`;

    const isNew = !season || season.includes('24') || season.includes('25') || season.includes('26');
    const isBestSeller = TOP_CLUBS.includes(team) || TOP_NATIONS.includes(team);
    
    const keywords = [
      `maillot ${team}`,
      `maillot ${team} ${season || ''}`,
      `maillot ${team} ${type}`,
      `maillot foot ${team} pas cher`,
      `achat maillot ${team}`,
      `boutique ${team}`,
      `kit football ${team}`
    ].filter(k => k.trim().length > 0);

    const badges: string[] = [];
    if (isNew) badges.push('Nouveau');
    if (isBestSeller) badges.push('Best-seller');
    if (isPlayerEdition) badges.push('Player Edition');

    products.push({
      id: slug,
      name,
      slug,
      price,
      image: images[0],
      hoverImage: images.length > 1 ? images[1] : undefined,
      images,
      category,
      team,
      season,
      type,
      folderName: folder,
      shortDescription,
      longDescription,
      isNew,
      isBestSeller,
      badges: badges.length > 0 ? badges : undefined,
      keywords
    });
  }

  // ==========================================
  // DEDUPLICATION
  // Use folderName as key to show all 1000 maillots
  // ==========================================
  const deduped = new Map<string, Product>();
  for (const product of products) {
    const key = product.folderName;

    const existing = deduped.get(key);
    if (!existing) {
      deduped.set(key, product);
    }
  }

  const uniqueProducts = Array.from(deduped.values());

  // Sort products: Top Clubs first, then Top Nations, then New, then alphabetical
  uniqueProducts.sort((a, b) => {
    const aIsTopClub = TOP_CLUBS.includes(a.team);
    const bIsTopClub = TOP_CLUBS.includes(b.team);
    if (aIsTopClub && !bIsTopClub) return -1;
    if (!aIsTopClub && bIsTopClub) return 1;

    const aIsTopNation = TOP_NATIONS.includes(a.team);
    const bIsTopNation = TOP_NATIONS.includes(b.team);
    if (aIsTopNation && !bIsTopNation) return -1;
    if (!aIsTopNation && bIsTopNation) return 1;

    // Inside same tier, put newest first
    if (a.isNew && !b.isNew) return -1;
    if (!a.isNew && b.isNew) return 1;

    return a.name.localeCompare(b.name);
  });

  cachedProducts = uniqueProducts;
  return uniqueProducts;
}

export function getProductBySlug(slug: string): Product | undefined {
  const products = getAllProducts();
  return products.find(p => p.slug === slug);
}

export function getProductsByTeam(team: string): Product[] {
  const products = getAllProducts();
  const normalizedTarget = normalizeTeamFromTokens(team.split(' '));
  return products.filter(p => p.team === normalizedTarget);
}

export function getProductsByType(type: string): Product[] {
  const products = getAllProducts();
  return products.filter(p => p.type.toLowerCase() === type.toLowerCase());
}

export function getRelatedProducts(product: Product, limit = 8): Product[] {
  const products = getAllProducts();
  const related: Product[] = [];
  const seen = new Set<string>([product.id]);

  // Priority 1: Same team
  const sameTeam = products.filter(p => p.team === product.team && !seen.has(p.id));
  for (const p of sameTeam.slice(0, limit)) {
    related.push(p);
    seen.add(p.id);
  }

  // Priority 2: Same type
  if (related.length < limit) {
    const sameType = products.filter(p => p.type === product.type && !seen.has(p.id));
    for (const p of sameType.slice(0, limit - related.length)) {
      related.push(p);
      seen.add(p.id);
    }
  }

  return related.slice(0, limit);
}

export function getAllClubs() {
  const products = getAllProducts();
  const clubMap = new Map<string, { name: string; slug: string; count: number }>();
  for (const p of products) {
    const slug = slugify(p.team, { lower: true, strict: true });
    const existing = clubMap.get(slug);
    if (existing) {
      existing.count++;
    } else {
      clubMap.set(slug, { name: p.team, slug, count: 1 });
    }
  }
  return Array.from(clubMap.values()).sort((a, b) => b.count - a.count);
}

export function getAllTypes() {
  const products = getAllProducts();
  const typeMap = new Map<string, { name: string; slug: string; count: number }>();
  for (const p of products) {
    const slug = slugify(p.type, { lower: true, strict: true });
    const existing = typeMap.get(slug);
    if (existing) {
      existing.count++;
    } else {
      typeMap.set(slug, { name: p.type, slug, count: 1 });
    }
  }
  return Array.from(typeMap.values()).sort((a, b) => b.count - a.count);
}

export function getAllSeasons() {
  const products = getAllProducts();
  const seasonMap = new Map<string, { name: string; slug: string; count: number }>();
  for (const p of products) {
    if (!p.season || p.season === 'Inconnue') continue;
    const slug = slugify(p.season, { lower: true, strict: true });
    const existing = seasonMap.get(slug);
    if (existing) {
      existing.count++;
    } else {
      seasonMap.set(slug, { name: p.season, slug, count: 1 });
    }
  }
  return Array.from(seasonMap.values()).sort((a, b) => b.count - a.count);
}
