import fs from 'fs';
import path from 'path';
import slugify from 'slugify';
import { Product } from '@/types';

// Load invalid images list (generated by scripts/filter-bad-images.js)
let invalidImageSet: Set<string> | null = null;
function getInvalidImages(): Set<string> {
  if (!invalidImageSet) {
    try {
      const filePath = path.join(process.cwd(), 'src', 'data', 'invalid-images.json');
      const data = JSON.parse(fs.readFileSync(filePath, 'utf-8')) as string[];
      invalidImageSet = new Set(data);
    } catch {
      invalidImageSet = new Set();
    }
  }
  return invalidImageSet;
}

const TEAM_ALIASES: Record<string, string> = {
  // Premier League
  'man u': 'Manchester United',
  'man utd': 'Manchester United',
  'manchester utd': 'Manchester United',
  'manchester': 'Manchester United', // often just called Manchester in generic folders
  'man city': 'Manchester City',
  'arsenal': 'Arsenal',
  'chelsea': 'Chelsea',
  'liverpool': 'Liverpool',
  'tottenham': 'Tottenham Hotspur',
  'tottenham hotspur': 'Tottenham Hotspur',
  'aston': 'Aston Villa',
  'aston villa': 'Aston Villa',
  'newcastle': 'Newcastle United',
  'newcastle united': 'Newcastle United',
  'leeds': 'Leeds United',
  'leeds united': 'Leeds United',
  'leicester': 'Leicester City',
  'leicester city': 'Leicester City',
  
  // La Liga
  'barca': 'FC Barcelona',
  'barcelona': 'FC Barcelona',
  'fc barcelona': 'FC Barcelona',
  'real': 'Real Madrid',
  'real madrid': 'Real Madrid',
  'atm': 'Atletico Madrid',
  'atletico': 'Atletico Madrid',
  'atletico madrid': 'Atletico Madrid',
  'atlético de madrid': 'Atletico Madrid',
  'bilbao': 'Athletic Bilbao',
  'athletic bilbao': 'Athletic Bilbao',
  'betis': 'Real Betis',
  'seville': 'Sevilla',
  'sevilla': 'Sevilla',
  'valencia': 'Valencia',
  
  // Serie A
  'juve': 'Juventus',
  'juventus': 'Juventus',
  'ac': 'AC Milan',
  'milan': 'AC Milan',
  'ac milan': 'AC Milan',
  'inter': 'Inter Milan',
  'inter milan': 'Inter Milan',
  'naples': 'Napoli',
  'napoli': 'Napoli',
  'roma': 'AS Roma',
  'lazio': 'Lazio',
  'fiorentina': 'Fiorentina',
  
  // Ligue 1
  'paris saintgermain': 'PSG',
  'paris saint germain': 'PSG',
  'paris': 'PSG',
  'psg': 'PSG',
  'ol': 'Olympique Lyonnais',
  'lyon': 'Olympique Lyonnais',
  'om': 'Olympique de Marseille',
  'marseille': 'Olympique de Marseille',
  'lille': 'LOSC Lille',
  'lens': 'RC Lens',
  'monaco': 'AS Monaco',
  'rennes': 'Stade Rennais',
  
  // Bundesliga
  'bayern': 'Bayern Munich',
  'bayern munich': 'Bayern Munich',
  'bvb': 'Borussia Dortmund',
  'dortmund': 'Borussia Dortmund',
  'borussia dortmund': 'Borussia Dortmund',
  'leverkusen': 'Bayer Leverkusen',
  'bayer leverkusen': 'Bayer Leverkusen',
  'leipzig': 'RB Leipzig',
  
  // Other Clubs
  'ajax': 'Ajax Amsterdam',
  'psv': 'PSV Eindhoven',
  'feyenoord': 'Feyenoord',
  'benfica': 'Benfica',
  'porto': 'FC Porto',
  'sporting': 'Sporting CP',
  'sporting cp': 'Sporting CP',
  'lisbon': 'Sporting CP',
  'celtic': 'Celtic FC',
  'rangers': 'Rangers FC',
  'galata': 'Galatasaray',
  'galatasaray': 'Galatasaray',
  'fenerbahçe': 'Fenerbahce',
  'fenerbahce': 'Fenerbahce',
  'besiktas': 'Besiktas',
  'boca': 'Boca Juniors',
  'boca juniors': 'Boca Juniors',
  'river': 'River Plate',
  'river plate': 'River Plate',
  'flamengo': 'Flamengo',
  'corinthians': 'Corinthians',
  'palmeiras': 'Palmeiras',
  'sao paulo': 'Sao Paulo',
  'miami': 'Inter Miami',
  'inter miami': 'Inter Miami',
  'la galaxy': 'LA Galaxy',
  'al nassr': 'Al Nassr',
  'al hilal': 'Al Hilal',
  'al ahli': 'Al Ahli',
  
  // Nations
  'france': 'France',
  'french': 'France',
  'argentine': 'Argentine',
  'argentina': 'Argentine',
  'bresil': 'Brésil',
  'brazil': 'Brésil',
  'brazilian': 'Brésil',
  'allemagne': 'Allemagne',
  'germany': 'Allemagne',
  'german': 'Allemagne',
  'espagne': 'Espagne',
  'spain': 'Espagne',
  'spanish': 'Espagne',
  'italie': 'Italie',
  'italy': 'Italie',
  'italian': 'Italie',
  'angleterre': 'Angleterre',
  'england': 'Angleterre',
  'english': 'Angleterre',
  'portugal': 'Portugal',
  'pays-bas': 'Pays-Bas',
  'netherlands': 'Pays-Bas',
  'dutch': 'Pays-Bas',
  'belgique': 'Belgique',
  'belgium': 'Belgique',
  'belgian': 'Belgique',
  'maroc': 'Maroc',
  'morocco': 'Maroc',
  'moroccan': 'Maroc',
  'algerie': 'Algérie',
  'algeria': 'Algérie',
  'algerian': 'Algérie',
  'senegal': 'Sénégal',
  'cameroun': 'Cameroun',
  'cameroon': 'Cameroun',
  'cote divoire': 'Côte d\'Ivoire',
  'ivory coast': 'Côte d\'Ivoire',
  'japon': 'Japon',
  'japan': 'Japon',
  'japanese': 'Japon',
  'mexique': 'Mexique',
  'mexico': 'Mexique',
  'mexican': 'Mexique',
  'colombie': 'Colombie',
  'colombia': 'Colombie',
  'uruguay': 'Uruguay',
  'chili': 'Chili',
  'chile': 'Chili'
};

export const TOP_CLUBS = [
  'Real Madrid', 'FC Barcelona', 'PSG', 'Manchester City', 'Arsenal', 
  'Manchester United', 'Liverpool', 'Chelsea', 'Bayern Munich', 
  'Juventus', 'AC Milan', 'Inter Milan', 'Atletico Madrid', 'Borussia Dortmund',
  'Olympique de Marseille', 'Olympique Lyonnais'
];

export const TOP_NATIONS = [
  'France', 'Argentine', 'Brésil', 'Allemagne', 'Espagne', 
  'Italie', 'Angleterre', 'Portugal', 'Maroc', 'Algérie', 'Sénégal'
];

function normalizeTeam(team: string): string {
  let t = team.toLowerCase().trim();
  
  // Pre-clean common garbage words and residual numbers from folder names
  t = t.replace(/['.]s\b/g, '')
       .replace(/^[.\s]+/, '') // Remove leading dots or spaces
       .replace(/^\d{4,6}/, '') // Remove leading dates like 2526, 202324, 0607
       .replace(/\b[sml]?\d?x+l\d?\b/gi, '') // Remove sizes like sxxl, 4xl, s4xl, xl5, etc.
       .replace(/\b[sml]\b/gi, '') // Remove single letter sizes
       .replace(/team/g, '')
       .replace(/football club/g, '')
       .replace(/fc\b/g, '')
       .replace(/cf\b/g, '')
       .replace(/version/g, '')
       .replace(/special/g, '')
       .replace(/casual/g, '')
       .replace(/thick/g, '')
       .replace(/pullover/g, '')
       .replace(/hoodie/g, '')
       .replace(/windbreaker/g, '')
       .replace(/suit/g, '')
       .replace(/fabric/g, '')
       .replace(/concepts/g, '')
       .replace(/collaboration/g, '')
       .replace(/limited/g, '')
       .replace(/commemorative/g, '')
       .replace(/outfit/g, '')
       .replace(/style/g, '')
       .replace(/advertisement/g, '')
       .replace(/derby/g, '')
       .replace(/withads/g, '')
       .replace(/withoutads/g, '')
       .replace(/stadium/g, '')
       .replace(/sxxl/g, '')
       .replace(/s4xl/g, '')
       .replace(/\d+$/g, '') // Remove trailing numbers
       .trim();

  // Remove leading dots again if any appeared after other cleans
  t = t.replace(/^[.\s]+/, '');

  // Check exact match first
  for (const [alias, realName] of Object.entries(TEAM_ALIASES)) {
    if (t === alias) return realName;
  }
  
  // Check includes
  for (const [alias, realName] of Object.entries(TEAM_ALIASES)) {
    // Only match whole words for includes to avoid false positives (e.g. "milan" in some random word)
    const regex = new RegExp(`\\b${alias}\\b`, 'i');
    if (regex.test(t)) {
      return realName;
    }
  }
  
  // If no alias found, try to extract team name by inserting spaces between camelCase words
  // This handles cases like "Acffiorentinasxxl" -> "Ac fiorentina"
  const withSpaces = t
    .replace(/([a-z])([A-Z])/g, '$1 $2') // Insert space before capital letters in camelCase
    .replace(/([a-z])([0-9])/g, '$1 $2') // Insert space before numbers
    .replace(/\s+/g, ' ') // Normalize multiple spaces
    .trim();
  
  // Clean it up and capitalize
  const cleaned = withSpaces.split(' ')
    .filter(w => w.length > 0) // Remove empty strings
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ')
    .trim();
  
  return cleaned || "Maillot de Football";
}

function parseFolderName(folderName: string) {
  let name = folderName.replace(/^#/, '').trim();
  
  // Clean trailing numbers after sizes like S-XXL3 -> S-XXL
  name = name.replace(/(S-[A-Z0-9XL]+)\d+$/i, '$1');
  
  let season: string | null = null;
  // Match seasons like 23-24, 23/24, 2023-2024, 0103 (01-03), 0304 (03-04), 0506, 0607
  const seasonMatch = name.match(/(20\d{2}[-/]\d{2}|\d{2}[-/]\d{2}|\b\d{4}\b|\b\d{2}\b)/);
  if (seasonMatch) {
    const raw = seasonMatch[1];
    if (raw.length === 4 && !raw.includes('-') && !raw.includes('/')) {
      season = raw.substring(0,2) + '-' + raw.substring(2,4);
    } else if (raw.length === 2) {
      season = '20' + raw; 
    } else {
      season = raw.replace('/', '-');
    }
    name = name.replace(seasonMatch[0], ' ').trim();
  }

  let type = 'Domicile'; // default home
  if (/away|extérieur/i.test(name)) type = 'Extérieur';
  if (/third/i.test(name)) type = 'Third';
  if (/retro|throwback/i.test(name)) type = 'Rétro';
  if (/training|jacket|survetement|veste|pantalon/i.test(name)) type = 'Training';
  if (/goalkeeper|gk|gardien/i.test(name)) type = 'Gardien';
  
  const category = /kids|enfant/i.test(name) || /16#-28#/i.test(name) ? 'Enfant' : 'Adulte';

  // Clean up team name
  let team = name
    .replace(/away|home|third|retro|game|shirt|jersey|long sleeve|short sleeve|jacket|kids|size|edition|domicile|extérieur|third|gardien|throwback|at |kit|player|anniversary|longsleeved|fabric|concepts|collaboration|limited|commemorative|outfit|style|advertisement|derby|withads|withoutads|stadium/ig, '')
    .replace(/\b[sml]?\d?x+l\d?\b/gi, '') // remove sizes like sxxl, 4xl
    .replace(/\b[SML0-9#-]+\b/g, '') // remove remaining sizes/numbers
    .replace(/[-(),]/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim();

  // Try to split camelCase words if team name is still concatenated (e.g., "acffiorentina" -> "ac fiorentina")
  if (team && !/\s/.test(team) && team.length > 3) {
    // Insert spaces before capital letters in camelCase
    const spaced = team.replace(/([a-z])([A-Z])/g, '$1 $2').trim();
    if (spaced !== team) {
      team = spaced;
    }
  }

  team = normalizeTeam(team);
  
  if (!team) team = "Maillot de Football";
    
  return { folderName, team, season, type, category };
}

// Global cache for performance
let cachedProducts: Product[] | null = null;

// Process products from JSON catalog
function processProductsFromCatalog(catalogData: Array<{folderName: string, images: string[]}>): Product[] {
  const products: Product[] = [];
  const slugs = new Set<string>();

  for (const item of catalogData) {
    const { folderName: folder, images: rawImages } = item;
    const { team, season, type, category } = parseFolderName(folder);
    
    // Encode images from catalog
    const images = rawImages;
    
    // Construct clean name
    let name = `Maillot ${team}`;
    if (type !== 'Domicile' && type !== 'Rétro' && type !== 'Training') {
      name += ` ${type}`;
    } else if (type === 'Rétro') {
      name = `Maillot Rétro ${team}`;
    } else if (type === 'Training') {
      name = `Survêtement/Training ${team}`;
    }

    if (season) {
      name += ` ${season}`;
    }
    
    if (category === 'Enfant') {
      name += ` (Enfant)`;
    }

    // Generate Slug
    let baseSlug = slugify(`${team} ${type} ${season || ''} ${category === 'Enfant' ? 'enfant' : ''}`, { lower: true, strict: true });
    let slug = baseSlug;
    let counter = 1;
    while (slugs.has(slug)) {
      slug = `${baseSlug}-${counter}`;
      counter++;
    }
    slugs.add(slug);

    if (images.length === 0) continue;

    // Detect Player Edition for pricing
    const isPlayerEdition = /player|edition/i.test(folder);
    const price = isPlayerEdition ? 34 : 29;
    
    const shortDescription = isPlayerEdition
      ? `Achetez le ${name} (Version Player) au meilleur prix sur KIT FOOTBALL. Maillot haute performance, coupe ajustée, tissu premium ultra-respirant. Livraison express 48h.`
      : `Commandez votre ${name} pas cher (29€) sur KIT FOOTBALL. Maillot de foot haute qualité, idéal pour le terrain ou les supporters. Stock limité, livraison rapide.`;
    
    let longDescription = isPlayerEdition
      ? `### Version Player Edition - Qualité Professionnelle\n\nPropulsez votre jeu au niveau supérieur avec le **${name} Version Player**. Ce maillot est la réplique exacte de celui porté par les joueurs sur le terrain.\n\n`
      : `### Maillot ${name} - Édition Supporter\n\nAffichez votre passion pour votre équipe avec le **${name}**. Conçu pour allier confort et style, ce maillot est parfait pour toutes les occasions.\n\n`;
    
    longDescription += `#### Caractéristiques techniques :\n`;
    longDescription += `- **Équipe officielle :** ${team}\n`;
    if (season) longDescription += `- **Saison :** ${season}\n`;
    longDescription += `- **Type de maillot :** ${type}\n`;
    longDescription += isPlayerEdition ? `- **Version :** Player Edition (Coupe athlétique ajustée)\n` : `- **Version :** Fan Edition (Coupe standard confortable)\n`;
    longDescription += `- **Tissu :** Technologie respirante pour une évacuation optimale de la transpiration\n`;
    longDescription += `- **Détails :** Logos brodés (Fan) ou thermocollés (Player) selon la version\n\n`;
    longDescription += `#### Pourquoi acheter sur KIT FOOTBALL ?\n`;
    longDescription += `- **Prix imbattable :** Votre maillot de foot à partir de 29€.\n`;
    longDescription += `- **Qualité Premium :** Finitions soignées et matériaux durables.\n`;
    longDescription += `- **Livraison Rapide :** Expédition sous 48h avec suivi.\n`;
    longDescription += `- **Satisfaction Garantie :** Service client réactif à votre écoute.\n\n`;
    longDescription += `*Disponible en tailles S, M, L, XL, XXL. Profitez-en avant la rupture de stock !*`;

    const isNew = !season || season.includes('24') || season.includes('25') || season.includes('26');
    const isBestSeller = TOP_CLUBS.includes(team) || TOP_NATIONS.includes(team);
    
    const keywords = [
      `maillot ${team}`,
      `maillot ${team} ${season || ''}`,
      `maillot ${team} ${type}`,
      `maillot foot ${team} pas cher`,
      `achat maillot ${team}`,
      `boutique ${team}`,
      `kit football ${team}`
    ].filter(k => k.trim().length > 0);

    const badges: string[] = [];
    if (isNew) badges.push('Nouveau');
    if (isBestSeller) badges.push('Best-seller');
    if (isPlayerEdition) badges.push('Player Edition');

    products.push({
      id: slug,
      name,
      slug,
      price,
      image: images[0],
      hoverImage: images.length > 1 ? images[1] : undefined,
      images,
      category,
      team,
      season,
      type,
      folderName: folder,
      shortDescription,
      longDescription,
      isNew,
      isBestSeller,
      badges: badges.length > 0 ? badges : undefined,
      keywords
    });
  }

  // ==========================================
  // DEDUPLICATION
  // Use folderName as key to show all 1000 maillots
  // ==========================================
  const deduped = new Map<string, Product>();
  for (const product of products) {
    const key = product.folderName;

    const existing = deduped.get(key);
    if (!existing) {
      deduped.set(key, product);
    }
  }

  const uniqueProducts = Array.from(deduped.values());

  // Sort products
  uniqueProducts.sort((a, b) => {
    const aIsTopClub = TOP_CLUBS.includes(a.team);
    const bIsTopClub = TOP_CLUBS.includes(b.team);
    if (aIsTopClub && !bIsTopClub) return -1;
    if (!aIsTopClub && bIsTopClub) return 1;

    const aIsTopNation = TOP_NATIONS.includes(a.team);
    const bIsTopNation = TOP_NATIONS.includes(b.team);
    if (aIsTopNation && !bIsTopNation) return -1;
    if (!aIsTopNation && bIsTopNation) return 1;

    if (a.isNew && !b.isNew) return -1;
    if (!a.isNew && b.isNew) return 1;

    return a.name.localeCompare(b.name);
  });

  cachedProducts = uniqueProducts;
  return uniqueProducts;
}

// Fallback products when maillots directory is not available - 100 best-selling jerseys
function getFallbackProducts(): Product[] {
  const topJerseys = [
    // Top Clubs - Domicile 2024-25
    { team: 'Real Madrid', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Real Madrid', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'FC Barcelona', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'FC Barcelona', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'PSG', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'PSG', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Manchester City', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Manchester City', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Arsenal', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Arsenal', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Liverpool', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Liverpool', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Manchester United', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Manchester United', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Bayern Munich', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Bayern Munich', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Inter Milan', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Inter Milan', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'AC Milan', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'AC Milan', type: 'Domicile', season: '24-25', isPlayer: true },
    
    // Top Clubs - Extérieur 2024-25
    { team: 'Real Madrid', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'FC Barcelona', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'PSG', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'Manchester City', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'Arsenal', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'Liverpool', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'Chelsea', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Chelsea', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'Juventus', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Juventus', type: 'Extérieur', season: '24-25', isPlayer: false },
    
    // National Teams 2024-25
    { team: 'France', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'France', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'France', type: 'Extérieur', season: '24-25', isPlayer: false },
    { team: 'Argentine', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Argentine', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Brésil', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Brésil', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Allemagne', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Espagne', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Espagne', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Portugal', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Portugal', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Angleterre', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Italie', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Pays-Bas', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Belgique', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Maroc', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Maroc', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Algérie', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Sénégal', type: 'Domicile', season: '24-25', isPlayer: false },
    
    // More Top Clubs
    { team: 'Atletico Madrid', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Borussia Dortmund', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Borussia Dortmund', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Napoli', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'AS Roma', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Tottenham Hotspur', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Newcastle United', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Olympique de Marseille', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Olympique Lyonnais', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'AS Monaco', type: 'Domicile', season: '24-25', isPlayer: false },
    
    // Retro Classics
    { team: 'Real Madrid', type: 'Rétro', season: '13-14', isPlayer: false },
    { team: 'FC Barcelona', type: 'Rétro', season: '10-11', isPlayer: false },
    { team: 'Manchester United', type: 'Rétro', season: '07-08', isPlayer: false },
    { team: 'AC Milan', type: 'Rétro', season: '06-07', isPlayer: false },
    { team: 'Arsenal', type: 'Rétro', season: '03-04', isPlayer: false },
    { team: 'France', type: 'Rétro', season: '98', isPlayer: false },
    { team: 'Brésil', type: 'Rétro', season: '02', isPlayer: false },
    { team: 'Argentine', type: 'Rétro', season: '86', isPlayer: false },
    
    // Third Kits
    { team: 'Real Madrid', type: 'Third', season: '24-25', isPlayer: false },
    { team: 'FC Barcelona', type: 'Third', season: '24-25', isPlayer: false },
    { team: 'PSG', type: 'Third', season: '24-25', isPlayer: false },
    { team: 'Manchester City', type: 'Third', season: '24-25', isPlayer: false },
    { team: 'Bayern Munich', type: 'Third', season: '24-25', isPlayer: false },
    
    // More Clubs
    { team: 'Benfica', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'FC Porto', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Sporting CP', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Ajax Amsterdam', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'PSV Eindhoven', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Celtic FC', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Rangers FC', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Galatasaray', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Fenerbahce', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Inter Miami', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Inter Miami', type: 'Domicile', season: '24-25', isPlayer: true },
    { team: 'Al Nassr', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Al Nassr', type: 'Domicile', season: '24-25', isPlayer: true },
    
    // More National Teams
    { team: 'Cameroun', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Côte d\'Ivoire', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Mexique', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Colombie', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Uruguay', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Japon', type: 'Domicile', season: '24-25', isPlayer: false },
    
    // Additional Popular Clubs
    { team: 'Aston Villa', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Leicester City', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Sevilla', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Valencia', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Lazio', type: 'Domicile', season: '24-25', isPlayer: false },
    { team: 'Fiorentina', type: 'Domicile', season: '24-25', isPlayer: false },
  ];

  return topJerseys.map((jersey, index) => {
    const price = jersey.isPlayer ? 34 : 29;
    const playerSuffix = jersey.isPlayer ? ' Player Edition' : '';
    const name = `Maillot ${jersey.team} ${jersey.type} ${jersey.season}${playerSuffix}`;
    const slug = slugify(name, { lower: true, strict: true });
    const id = `${slug}-${index}`;
    
    const shortDescription = jersey.isPlayer 
      ? `Version Player Edition du ${name.toLowerCase()}. Qualité professionnelle, coupe athlétique, tissu technique premium.`
      : `Découvrez le ${name.toLowerCase()}. Conçu pour les passionnés, ce modèle offre un confort optimal sur le terrain comme au quotidien.`;
    
    let longDescription = jersey.isPlayer
      ? `Version Player Edition authentique du ${name.toLowerCase()}. Identique aux maillots portés par les joueurs professionnels.\n\n`
      : `Affichez fièrement vos couleurs avec ce superbe ${name.toLowerCase()}. Que vous soyez dans les gradins ou sur le terrain, ce modèle allie style et performance.\n\n`;
    
    longDescription += `- **Équipe :** ${jersey.team}\n`;
    longDescription += `- **Saison :** ${jersey.season}\n`;
    longDescription += `- **Type :** ${jersey.type}\n`;
    longDescription += jersey.isPlayer ? `- **Version :** Player Edition (Qualité Pro)\n` : `- **Version :** Fan Edition\n`;
    longDescription += `- **Coupe :** ${jersey.isPlayer ? 'Athlétique ajustée' : 'Standard confortable'}\n`;
    longDescription += `- **Qualité :** ${jersey.isPlayer ? 'Tissu technique premium, ultra-respirant' : 'Tissu respirant et confortable'}\n\n`;
    longDescription += `*Tailles disponibles : S, M, L, XL, XXL. Livraison rapide 48h.*`;

    const isNew = jersey.season.includes('24') || jersey.season.includes('25');
    const isBestSeller = !jersey.isPlayer && ['Real Madrid', 'FC Barcelona', 'PSG', 'France', 'Argentine', 'Manchester City'].includes(jersey.team);

    const badges: string[] = [];
    if (isNew) badges.push('Nouveau');
    if (isBestSeller) badges.push('Best-seller');
    if (jersey.isPlayer) badges.push('Player Edition');

    return {
      id,
      name,
      slug,
      price,
      image: '/Images/maillot-psg-domicile-2024-25.jpg', // Placeholder
      hoverImage: undefined,
      images: ['/Images/maillot-psg-domicile-2024-25.jpg'],
      category: 'Adulte',
      team: jersey.team,
      season: jersey.season,
      type: jersey.type,
      folderName: slug,
      shortDescription,
      longDescription,
      isNew,
      isBestSeller,
      badges: badges.length > 0 ? badges : undefined
    };
  });
}

export function getAllProducts(): Product[] {
  if (cachedProducts) return cachedProducts;

  const productsDir = path.join(process.cwd(), 'public', 'maillots');
  
  // Try to load from JSON catalog if directory doesn't exist
  if (!fs.existsSync(productsDir)) {
    console.warn(`Directory not found: ${productsDir}, trying JSON catalog`);
    try {
      const catalogPath = path.join(process.cwd(), 'src', 'data', 'maillots-catalog.json');
      if (fs.existsSync(catalogPath)) {
        const catalogData = JSON.parse(fs.readFileSync(catalogPath, 'utf-8'));
        return processProductsFromCatalog(catalogData);
      }
    } catch (error) {
      console.error('Error loading catalog:', error);
    }
    console.warn('JSON catalog not found, using fallback products');
    return getFallbackProducts();
  }

  const folders = fs.readdirSync(productsDir, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);

  const products: Product[] = [];
  const slugs = new Set<string>();

  for (const folder of folders) {
    const { team, season, type, category } = parseFolderName(folder);
    
    // Construct clean name
    let name = `Maillot ${team}`;
    if (type !== 'Domicile' && type !== 'Rétro' && type !== 'Training') {
      name += ` ${type}`;
    } else if (type === 'Rétro') {
      name = `Maillot Rétro ${team}`;
    } else if (type === 'Training') {
      name = `Survêtement/Training ${team}`;
    }

    if (season) {
      name += ` ${season}`;
    }
    
    if (category === 'Enfant') {
      name += ` (Enfant)`;
    }

    // Generate Slug
    let baseSlug = slugify(`${team} ${type} ${season || ''} ${category === 'Enfant' ? 'enfant' : ''}`, { lower: true, strict: true });
    let slug = baseSlug;
    let counter = 1;
    while (slugs.has(slug)) {
      slug = `${baseSlug}-${counter}`;
      counter++;
    }
    slugs.add(slug);

    // Get images, filtering out invalid ones
    const folderPath = path.join(productsDir, folder);
    const files = fs.readdirSync(folderPath);
    const badImages = getInvalidImages();
    const images = files
      .filter(f => /\.(jpg|jpeg|png|webp|avif)$/i.test(f))
      .map(f => `/maillots/${folder}/${f}`)
      .filter(imgPath => !badImages.has(imgPath));

    if (images.length === 0) continue; // Skip if no valid images

    // Sort images: prefer _1 filename as cover, then natural sort
    images.sort((a, b) => {
      const aIsMain = a.includes('_1.') ? -1 : 0;
      const bIsMain = b.includes('_1.') ? -1 : 0;
      if (aIsMain !== bIsMain) return aIsMain - bIsMain;
      return a.localeCompare(b, undefined, { numeric: true });
    });

    // Detect Player Edition for pricing
    const isPlayerEdition = /player|edition/i.test(folder);
    const price = isPlayerEdition ? 34 : 29;
    
    const shortDescription = isPlayerEdition
      ? `Achetez le ${name} (Version Player) au meilleur prix sur KIT FOOTBALL. Maillot haute performance, coupe ajustée, tissu premium ultra-respirant. Livraison express 48h.`
      : `Commandez votre ${name} pas cher (29€) sur KIT FOOTBALL. Maillot de foot haute qualité, idéal pour le terrain ou les supporters. Stock limité, livraison rapide.`;
    
    let longDescription = isPlayerEdition
      ? `### Version Player Edition - Qualité Professionnelle\n\nPropulsez votre jeu au niveau supérieur avec le **${name} Version Player**. Ce maillot est la réplique exacte de celui porté par les joueurs sur le terrain.\n\n`
      : `### Maillot ${name} - Édition Supporter\n\nAffichez votre passion pour votre équipe avec le **${name}**. Conçu pour allier confort et style, ce maillot est parfait pour toutes les occasions.\n\n`;
    
    longDescription += `#### Caractéristiques techniques :\n`;
    longDescription += `- **Équipe officielle :** ${team}\n`;
    if (season) longDescription += `- **Saison :** ${season}\n`;
    longDescription += `- **Type de maillot :** ${type}\n`;
    longDescription += isPlayerEdition ? `- **Version :** Player Edition (Coupe athlétique ajustée)\n` : `- **Version :** Fan Edition (Coupe standard confortable)\n`;
    longDescription += `- **Tissu :** Technologie respirante pour une évacuation optimale de la transpiration\n`;
    longDescription += `- **Détails :** Logos brodés (Fan) ou thermocollés (Player) selon la version\n\n`;
    longDescription += `#### Pourquoi acheter sur KIT FOOTBALL ?\n`;
    longDescription += `- **Prix imbattable :** Votre maillot de foot à partir de 29€.\n`;
    longDescription += `- **Qualité Premium :** Finitions soignées et matériaux durables.\n`;
    longDescription += `- **Livraison Rapide :** Expédition sous 48h avec suivi.\n`;
    longDescription += `- **Satisfaction Garantie :** Service client réactif à votre écoute.\n\n`;
    longDescription += `*Disponible en tailles S, M, L, XL, XXL. Profitez-en avant la rupture de stock !*`;

    const isNew = !season || season.includes('24') || season.includes('25') || season.includes('26');
    const isBestSeller = TOP_CLUBS.includes(team) || TOP_NATIONS.includes(team);
    
    const keywords = [
      `maillot ${team}`,
      `maillot ${team} ${season || ''}`,
      `maillot ${team} ${type}`,
      `maillot foot ${team} pas cher`,
      `achat maillot ${team}`,
      `boutique ${team}`,
      `kit football ${team}`
    ].filter(k => k.trim().length > 0);

    const badges: string[] = [];
    if (isNew) badges.push('Nouveau');
    if (isBestSeller) badges.push('Best-seller');
    if (isPlayerEdition) badges.push('Player Edition');

    products.push({
      id: slug,
      name,
      slug,
      price,
      image: images[0],
      hoverImage: images.length > 1 ? images[1] : undefined,
      images,
      category,
      team,
      season,
      type,
      folderName: folder,
      shortDescription,
      longDescription,
      isNew,
      isBestSeller,
      badges: badges.length > 0 ? badges : undefined,
      keywords
    });
  }

  // ==========================================
  // DEDUPLICATION
  // Use folderName as key to show all 1000 maillots
  // ==========================================
  const deduped = new Map<string, Product>();
  for (const product of products) {
    const key = product.folderName;

    const existing = deduped.get(key);
    if (!existing) {
      deduped.set(key, product);
    }
  }

  const uniqueProducts = Array.from(deduped.values());

  // Sort products: Top Clubs first, then Top Nations, then New, then alphabetical
  uniqueProducts.sort((a, b) => {
    const aIsTopClub = TOP_CLUBS.includes(a.team);
    const bIsTopClub = TOP_CLUBS.includes(b.team);
    if (aIsTopClub && !bIsTopClub) return -1;
    if (!aIsTopClub && bIsTopClub) return 1;

    const aIsTopNation = TOP_NATIONS.includes(a.team);
    const bIsTopNation = TOP_NATIONS.includes(b.team);
    if (aIsTopNation && !bIsTopNation) return -1;
    if (!aIsTopNation && bIsTopNation) return 1;

    // Inside same tier, put newest first
    if (a.isNew && !b.isNew) return -1;
    if (!a.isNew && b.isNew) return 1;

    return a.name.localeCompare(b.name);
  });

  cachedProducts = uniqueProducts;
  return uniqueProducts;
}

export function getProductBySlug(slug: string): Product | undefined {
  const products = getAllProducts();
  return products.find(p => p.slug === slug);
}

export function getProductsByTeam(team: string): Product[] {
  const products = getAllProducts();
  const normalizedTarget = normalizeTeam(team);
  return products.filter(p => p.team === normalizedTarget);
}

export function getProductsByType(type: string): Product[] {
  const products = getAllProducts();
  return products.filter(p => p.type.toLowerCase() === type.toLowerCase());
}

export function getRelatedProducts(product: Product, limit = 8): Product[] {
  const products = getAllProducts();
  const related: Product[] = [];
  const seen = new Set<string>([product.id]);

  // Priority 1: Same team
  const sameTeam = products.filter(p => p.team === product.team && !seen.has(p.id));
  for (const p of sameTeam.slice(0, limit)) {
    related.push(p);
    seen.add(p.id);
  }

  // Priority 2: Same type
  if (related.length < limit) {
    const sameType = products.filter(p => p.type === product.type && !seen.has(p.id));
    for (const p of sameType.slice(0, limit - related.length)) {
      related.push(p);
      seen.add(p.id);
    }
  }

  return related.slice(0, limit);
}

export function getAllClubs() {
  const products = getAllProducts();
  const clubMap = new Map<string, { name: string; slug: string; count: number }>();
  for (const p of products) {
    const slug = slugify(p.team, { lower: true, strict: true });
    const existing = clubMap.get(slug);
    if (existing) {
      existing.count++;
    } else {
      clubMap.set(slug, { name: p.team, slug, count: 1 });
    }
  }
  return Array.from(clubMap.values()).sort((a, b) => b.count - a.count);
}

export function getAllTypes() {
  const products = getAllProducts();
  const typeMap = new Map<string, { name: string; slug: string; count: number }>();
  for (const p of products) {
    const slug = slugify(p.type, { lower: true, strict: true });
    const existing = typeMap.get(slug);
    if (existing) {
      existing.count++;
    } else {
      typeMap.set(slug, { name: p.type, slug, count: 1 });
    }
  }
  return Array.from(typeMap.values()).sort((a, b) => b.count - a.count);
}

export function getAllSeasons() {
  const products = getAllProducts();
  const seasonMap = new Map<string, { name: string; slug: string; count: number }>();
  for (const p of products) {
    if (!p.season || p.season === 'Inconnue') continue;
    const slug = slugify(p.season, { lower: true, strict: true });
    const existing = seasonMap.get(slug);
    if (existing) {
      existing.count++;
    } else {
      seasonMap.set(slug, { name: p.season, slug, count: 1 });
    }
  }
  return Array.from(seasonMap.values()).sort((a, b) => b.count - a.count);
}
